# Generated by Django 4.0.4 on 2022-05-16 09:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
