# Generated by Django 4.0.4 on 2022-05-16 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Положение')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Место работы')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Место жительство')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Номер телефона', max_length=31, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('web', models.URLField(blank=True, verbose_name='Ссылка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sitestatus', models.CharField(choices=[('Новый', 'Новый сайт'), ('Действующий', 'Действующий сайт')], max_length=20, verbose_name='Статус')),
                ('prioritystatus', models.CharField(choices=[('Н', 'Недавно - 1 неделя или меньше'), ('С', 'Средний - 2 или 4 недели'), ('Д', 'Дольше  - Не действительный')], max_length=20, verbose_name='Приоритет')),
                ('jobfile', models.FileField(blank=True, upload_to='uploads/', verbose_name='Файл')),
                ('submitted', models.DateField(auto_now_add=True, verbose_name='Представлен')),
                ('quotedate', models.DateField(blank=True, null=True, verbose_name='Дата предложения')),
                ('quoteprice', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Цена')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Предложении',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
